### PR TITLE
fix(notice): fix limit 1 on useNotice does not work

### LINKED ISSUE #695: Limit 1 on `useNotice` does not work
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.3

### Description

When I set the notification limit to 1, I expected the number of notifications to be limited to 1, but it kept stacking instead.

### Link to Reproduction

_No response_

### Steps to Reproduce

1. Go to https://yamada-ui.com/styled-system/notification#limiting-the-number-of-displays
2. Change `limit` to 1
3. Click `Show notification` multiple times
4. See it not limiting to 1

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by 108yen**
Closes #695 

## Description

fix limit 1 on useNotice does not work

## Current behavior (updates)

Setting the limit value to 1 does not limit the number of displays.

## New behavior

If the limit is set to 1, only one is displayed.
If an invalid value such as -1 is set for the limit value, it is ignored.

## Additional Information
NIL

### CODE REVIEW

**Review by illionillion — CHANGES_REQUESTED** [review]
@108yen 
When I press the button quickly and repeatedly, sometimes more than one notice appears, even when the limit value is 1.

If Yamada UI uses framer-motion internally, this may be a bug of it.

https://github.com/hirotomoyamada/yamada-ui/assets/60034520/476be5cb-2617-443a-8778-a2db3c065aa6

**Comment by 108yen** [comment]
@illionillion 
I think it is this isssue.
https://github.com/framer/motion/issues/2462

Removing AnimatePresence in `notice-provider.tsx` will work correctly.
```tsx:
<AnimatePresence initial={false}>
    {notices.map((notice) => (
      <NoticeComponent key={notice.id} variants={variants} {...notice} />
    ))}
</AnimatePresence>
```

**Comment by illionillion** [comment]
> @illionillion I think it is this isssue. [framer/motion#2462](https://github.com/framer/motion/issues/2462)
> 
> Removing AnimatePresence in `notice-provider.tsx` will work correctly.
> 
> ```
> <AnimatePresence initial={false}>
>     {notices.map((notice) => (
>       <NoticeComponent key={notice.id} variants={variants} {...notice} />
>     ))}
> </AnimatePresence>
> ```

@108yen 
Thanks.
Please correct it that way.

**Comment by 108yen** [comment]
@illionillion 
If you remove AnimatePresence, the bug will be fixed, but the animation won’t be rendered. Is that okay? Since it’s a minor bug, waiting for a fix in framer-motion might be a good idea

https://github.com/hirotomoyamada/yamada-ui/assets/9676316/0e82c9d3-c4c1-44c7-86a6-e468c4b52581

**Comment by illionillion** [comment]
> @illionillion If you remove AnimatePresence, the bug will be fixed, but the animation won’t be rendered. Is that okay? Since it’s a minor bug, waiting for a fix in framer-motion might be a good idea
> 
>  notice.mp4

That's not good.
Let's wait for the framer-motion to fix it.
I think it is good to merge.

**Review by illionillion — APPROVED** [review]
Approved

**Pull request merged**
