### PR TITLE
test(stat): add test cases for color scheme, center content, decrease…

### LINKED ISSUE #625: Add tests for `@yamada-ui/stat`
related: #74

### Description

Currently, no tests in `@yamada-ui/stat`. In the future, I feel the need for testing when operating `@yamada-ui/stat`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

### PR DESCRIPTION
**Pull request by Evande1**
Closes #625 

## Description
Add test cases for color scheme, center content, decrease icon

## Current behavior (updates)
NIL

## New behavior
NIL
## Is this a breaking change (Yes/No):
No

### CODE REVIEW

**Comment by hirotomoyamada** [comment]
Hi, thanks for the PR.

Please don't include the `changelog` as this is just a test addition.

**Comment by hirotomoyamada** [comment]
@Evande1 

Hi, thanks for the PR.

Please do not include the `changelog` as this is just a test addition.

This does not apply if a defect is found during a test run and the main unit is fixed.

**Comment by Evande1** [comment]
@hirotomoyamada 
Hi, i just removed the ```changeset```, does that remove ```changelog``` from the commit?

**Review by hirotomoyamada — APPROVED** [review]

**Comment by hirotomoyamada** [comment]
Thanks!

**Pull request merged**
